page_analyzer/models.py
from datetime import datetime
from typing import Optional, List, Dict, Union
from urllib.parse import urlparse

import validators
from pydantic import BaseModel, field_validator, Field

from page_analyzer.services.utils import get_date_now

URL_MAX_LENGTH = 255


class URLBaseMixin(BaseModel):
    id: Optional[int] = None
    created_at: datetime = Field(default_factory=get_date_now)


class URLModel(URLBaseMixin):
    name: str = Field(max_length=URL_MAX_LENGTH)

    @field_validator('name')
    def validate_url(cls, value: str) -> str:

        if not validators.url(value):
            raise ValueError('Invalid url address')
        url = urlparse(value)
        return f'{url.scheme}://{url.netloc}'.lower()


class URLChecks(URLBaseMixin):
    url_id: int
    status_code: Optional[int] = None
    h1: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None


class URLSModel(URLModel):
    url_checks: Optional[List[URLChecks]] = []

    @field_validator('url_checks')
    def validate_url_checks(cls, value: List) -> List[
        Dict[str, Union[str, int]]
    ]:
        value.sort(key=lambda x: -x.id)
        return value

page_analyzer/__init__.py
import os

from dotenv import load_dotenv
from flask import Flask

load_dotenv()


def create_app(test_config=None):
    _app = Flask(__name__)
    _app.config.from_mapping(
        SECRET_KEY=os.getenv('SECRET_KEY'),
        DATABASE_URL=os.getenv('DATABASE_URL')
    )

    if test_config:
        _app.config.from_mapping(test_config)

    from page_analyzer.db import init_app
    init_app(_app)

    from page_analyzer import views
    _app.register_blueprint(views.bp)
    _app.add_url_rule('/', endpoint='index')

    return _app


app = create_app()

page_analyzer/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

from page_analyzer.db import get_db
from page_analyzer.services.check_url import CheckURLService
from page_analyzer.services.url import URLService

bp = Blueprint('page_analyzer', __name__)


@bp.get('/')
def index():
    """Главная страница."""

    return render_template('index.html')


@bp.get('/urls')
def get_urls():
    """Страница со всеми url."""

    db = get_db()
    url_service = URLService(db=db)
    items = url_service.get_all_urls()

    return render_template('urls.html', items=items)


@bp.get('/urls/<int:url_id>')
def get_url(url_id):
    """Страница c url с выдачей по id."""

    db = get_db()
    url_service = URLService(db=db)
    item = url_service.get_json_by_id(url_id)
    return render_template('url.html', item=item)


@bp.post('/urls')
def post_url():
    """ Проверяет есть ли url в базе,
    добавляет в базу или берет из базы существующий,
    редиректит на страницу с url."""

    url = request.form['url']
    db = get_db()
    url_service = URLService(db=db)
    result = url_service.insert_url(url)
    flash(*result['message'])
    if result['item']:
        return redirect(
            url_for(
                'page_analyzer.get_url',
                url_id=result['item'].id),
        )
    return redirect(url_for('index'))


@bp.post('/urls/<int:url_id>/checks')
def post_url_check(url_id):
    """Обработчик маршрута проверки"""

    db = get_db()
    check_url_service = CheckURLService(db=db)

    result_message = check_url_service.check(url_id)
    flash(*result_message)
    return redirect(
        url_for(
            'page_analyzer.get_url',
            url_id=url_id),
    )

page_analyzer/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Third project for Hexlet.io">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <title>Анализатор страниц</title>
  </head>
  <body class="min-vh-100 d-flex flex-column">
  <header class="flex-shrink-0">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="{{ url_for('index') }}">Анализатор страниц</a>
        <div id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link " href="/urls">Сайты</a></li>
            </ul>
      </div>
    </nav>

  </header>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
      {% for category, message in messages %}
        <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
  {% endwith %}


  <main class="flex-grow-1">
    <div class="container-lg mt-3">
      <h1>{% block title %}{% endblock %}</h1>
        {% block content %}{% endblock %}
    </div>
  </main>

  <footer class="border-top py-3 mt-5 flex-shrink-0">
  <div class="container-lg">
    <div class="text-center">
      <a href="https://ru.hexlet.io/" target="_blank">Hexlet</a>
    </div>
  </div>
</footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

page_analyzer/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
    <h1 class="display-3">Анализатор страниц</h1>
    <p class="lead">Бесплатно проверяйте сайты на SEO-пригодность</p>
    <form action="{{ url_for('page_analyzer.post_url')}}" method="post" class="d-flex justify-content-center" required>
        <input type="text" name="url" placeholder="https://www.example.com" value=""  class="form-control form-control-lg">
        <input type="submit" class="btn btn-primary  btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
    </form>
  </div>
</div>
{% endblock %}

page_analyzer/templates/url.html
{% extends 'base.html' %}
{% block title %}Сайт: {{ item.url }}{% endblock %}

{% block content %}
<div class="table-responsive">
  <table class="table table-bordered table-hover text-nowrap" data-test="url">
    <tbody>
    <tr>
      <td>ID</td>
      <td>{{ item.id }}</td>
    </tr>
    <tr>
      <td>Имя</td>
      <td>{{ item.name }}</td>
    </tr>
    <tr>
      <td>Дата создания</td>
      <td>{{ item.created_at.strftime('%Y-%m-%d')}}</td>
    </tr>
    </tbody>
  </table>
</div>

<h2 class="mt-5 mb-3">Проверки</h2>

<form method="post" action="{{ url_for('page_analyzer.post_url_check', url_id=item.id) }}">
  <input type="submit" class="btn btn-primary" value="Запустить проверку">
</form>

<div>
    <table class="table table-bordered table-hover mt-2" data-test="checks">
    <thead>
      <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
      </tr>
    </thead>
      <tbody>
    {% if item.url_checks %}
    {% for check in item.url_checks %}
    <tr>
        <td>{{ check.id }}</td>
        <td>{{ check.status_code|default('', true) }}</td>
        <td>{{ check.h1|default('', true) }}</td>
        <td>{{ check.title|default('', true) }}</td>
        <td>{{ check.description|default('', true) }}</td>
        <td>{{ check.created_at.strftime('%Y-%m-%d') }}</td>
    </tr>
    {% endfor %}
    {% endif %}
    </tbody>
    </table>
  </div>

{% endblock %}

page_analyzer/templates/urls.html
{% extends 'base.html' %}
{% block title %}Сайты{% endblock %}

{% block content %}
<div class="table-responsive">
  <table class="table table-bordered table-hover text-nowrap" data-test="urls">
    <thead>
    <tr>
      <th>ID</th>
      <th>Имя</th>
      <th>Последняя проверка</th>
      <th>Код ответа</th>
    </tr>
    </thead>
    <tbody>

    {% if items %}
    {% for item in items %}
    <tr>
          <td>{{ item.id }}</td>
          <td>
            <a href="{{ url_for('page_analyzer.get_url', url_id=item.id) }}">
              {{ item.name }}
            </a>
          </td>
          {% if item.url_checks %}
          {% for url_checks in item.url_checks %}
          <td>{{ url_checks.created_at.strftime('%Y-%m-%d') }}</td>
          <td>{{ url_checks.status_code }}</td>
          {% endfor %}
          {% else %}
          <td></td>
          <td></td>
          {% endif %}
    </tr>
    {% endfor %}
    {% endif %}

    </tbody>
  </table>
</div>
{% endblock %}